name: .NET 5

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '*.md'

jobs:
  build-windows:

    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT : true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.300'
    - name: Install dependencies
      run: dotnet restore ToolCustomiser
    - name: Build
      run: dotnet build --configuration Release ToolCustomiser
    - name: Test
      run: dotnet test -v n ToolCustomiser
      
    - name: Publish windows (x64)
      run: dotnet publish -c Release -r win-x64 ToolCustomiser
      
    - name: Upload artifact windows (x64)
      uses: actions/upload-artifact@v2
      with:
        name: win-x64
        path: ToolCustomiser/bin/Release/net5.0/win-x64/publish/
        
    - name: Publish windows (arm64)
      run: dotnet publish -c Release -r win-arm64 ToolCustomiser
      
    - name: Upload artifact windows (arm64)
      uses: actions/upload-artifact@v2
      with:
        name: win-arm64
        path: ToolCustomiser/bin/Release/net5.0/win-arm64/publish/
        
  build-linux:

    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT : true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.300'
    - name: Install dependencies
      run: dotnet restore ToolCustomiser
    - name: Build
      run: dotnet build --configuration Release ToolCustomiser
    - name: Test
      run: dotnet test -v n ToolCustomiser
      
    - name: Publish Linux (x64)
      run: dotnet publish -c Release -r linux-x64 ToolCustomiser
      
    - name: Upload artifact Linux (x64)
      uses: actions/upload-artifact@v2
      with:
        name: linux-x64
        path: ToolCustomiser/bin/Release/net5.0/linux-x64/publish/
        
      
  release:
    if: |
      github.event.action != 'pull_request' &&
      github.ref == 'refs/heads/master' &&
      github.repository == 'num0005/ToolCustomiser'
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
    - name: Compress artifacts
      run: |
        zip -r win-x64.zip win-x64
        zip -r win-arm64.zip win-arm64
        zip -r linux-x64.zip linux-x64
#        zip -r linux-arm64.zip linux-arm64
#        zip -r osx-x64.zip osx-x64
#        zip -r generic.zip generic
#        zip -r osx.11.0-arm64.zip osx.11.0-arm64
    - uses: ncipollo/release-action@v1
      with:
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "*.zip"
        tag: ${{ github.run_id }}
